In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
data = pd.read_csv('Dataset_challenge.csv')

X_data = data.drop(columns=['Outcome'])  
y_data = data['Outcome'] 

print(X_data)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [4]:
def normalize_data(data):
    if isinstance(data, pd.DataFrame):
        normalized_df = data.copy()
        for column in data.columns:
            max_value = data[column].max()
            normalized_df[column] = data[column] / max_value
        return normalized_df
    else:
        max_value = data.max()
        normalized_series = data / max_value
        return normalized_series

In [5]:
data = pd.read_csv('Dataset_challenge.csv')

X_data = data.drop(columns=['Outcome'])  
y_data = data['Outcome'] 

X_data = normalize_data(X_data)

print(X_data)

     Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.352941  0.743719       0.590164       0.353535  0.000000  0.500745   
1       0.058824  0.427136       0.540984       0.292929  0.000000  0.396423   
2       0.470588  0.919598       0.524590       0.000000  0.000000  0.347243   
3       0.058824  0.447236       0.540984       0.232323  0.111111  0.418778   
4       0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   
..           ...       ...            ...            ...       ...       ...   
763     0.588235  0.507538       0.622951       0.484848  0.212766  0.490313   
764     0.117647  0.613065       0.573770       0.272727  0.000000  0.548435   
765     0.294118  0.608040       0.590164       0.232323  0.132388  0.390462   
766     0.058824  0.633166       0.491803       0.000000  0.000000  0.448584   
767     0.058824  0.467337       0.573770       0.313131  0.000000  0.453055   

     DiabetesPedigreeFunction       Age

In [6]:
X_train = X_data.iloc[1:]
X_test = X_data.iloc[595:]
y_train = y_data.iloc[1:]
y_test = y_data.iloc[595:]
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)
# Chuyển đổi DataFrames thành numpy arrays
X_train_np = X_train.to_numpy().T
X_test_np = X_test.to_numpy().T
y_train_np = y_train.to_numpy().T
y_test_np = y_test.to_numpy().T

# Kiểm tra kết quả
print(X_train_np)  
print(y_train_np) 
print(X_train_np.shape)
print(X_train.shape)

[[0.05882353 0.47058824 0.05882353 ... 0.29411765 0.05882353 0.05882353]
 [0.42713568 0.91959799 0.44723618 ... 0.6080402  0.63316583 0.46733668]
 [0.54098361 0.52459016 0.54098361 ... 0.59016393 0.49180328 0.57377049]
 ...
 [0.39642325 0.34724292 0.41877794 ... 0.390462   0.4485842  0.45305514]
 [0.14504132 0.27768595 0.06900826 ... 0.10123967 0.14421488 0.13016529]
 [0.38271605 0.39506173 0.25925926 ... 0.37037037 0.58024691 0.28395062]]
[0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1
 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1
 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1
 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1 0
 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1
 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 

In [7]:
def init_params():
    W1 = np.random.rand(10, 8) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(2, 10) - 0.5
    b2 = np.random.rand(2, 1) - 0.5
    print(W1)
    print(W2)
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / np.sum(np.exp(Z), axis=0, keepdims=True)
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y, num_classes):
    one_hot_Y = np.zeros((num_classes, Y.size))
    one_hot_Y[Y, np.arange(Y.size)] = 1
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W2, X, Y):
    m = X.shape[0]  
    one_hot_Y = one_hot(Y, A2.shape[0])  

    dZ2 = A2 - one_hot_Y
    dW2 = dZ2.dot(A1.T) / m
    db2 = np.sum(dZ2) / m

    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = dZ1.dot(X.T) / m
    db1 = np.sum(dZ1) / m

    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, vW1, vb1, vW2, vb2, dW1, db1, dW2, db2, alpha, beta):
    vW1 = beta * vW1 + (1 - beta) * dW1
    vb1 = beta * vb1 + (1 - beta) * db1
    vW2 = beta * vW2 + (1 - beta) * dW2
    vb2 = beta * vb2 + (1 - beta) * db2

    W1 = W1 - alpha * vW1
    b1 = b1 - alpha * vb1
    W2 = W2 - alpha * vW2
    b2 = b2 - alpha * vb2

    return W1, b1, W2, b2, vW1, vb1, vW2, vb2

In [8]:
def get_predictions(A2):
    return np.argmax(A2, axis=0)

def get_accuracy(predictions, Y):
    return np.sum(predictions == Y) / Y.size

# def SGD_with_momentum(X, Y, alpha, iterations, batch_size, beta=0.9):
#     W1, b1, W2, b2 = init_params()
#     vW1, vb1, vW2, vb2 = np.zeros_like(W1), np.zeros_like(b1), np.zeros_like(W2), np.zeros_like(b2)
#     n = X.shape[1]

#     for i in range(iterations):
#         permutation = np.random.permutation(n)
#         X_shuffled = X[:, permutation]
#         Y_shuffled = Y[permutation]

#         for j in range(0, n, batch_size):
#             X_batch = X_shuffled[:, j:j + batch_size]
#             Y_batch = Y_shuffled[j:j + batch_size]

#             Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X_batch)

#             dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W2, X_batch, Y_batch)

#             W1, b1, W2, b2, vW1, vb1, vW2, vb2 = update_params(
#                 W1, b1, W2, b2, vW1, vb1, vW2, vb2, dW1, db1, dW2, db2, alpha, beta
#             )

#         if i % 10 == 0:
#             predictions = get_predictions(A2)
#             accuracy = get_accuracy(predictions, Y_batch)
#             print(f"Iteration {i}, Accuracy: {accuracy:.4f}")

#     return W1, b1, W2, b2

def train_with_epoch(X, Y, alpha, epochs, batch_size, beta=0.9):
    W1, b1, W2, b2 = init_params()

    # Khởi tạo các giá trị động lượng (momentum) ban đầu bằng 0
    vW1, vb1, vW2, vb2 = np.zeros_like(W1), np.zeros_like(b1), np.zeros_like(W2), np.zeros_like(b2)
    n = X.shape[1]

    for epoch in range(epochs):
        # Xáo trộn dữ liệu ở mỗi epoch
        permutation = np.random.permutation(n)
        X_shuffled = X[:, permutation]
        Y_shuffled = Y[permutation]

        for j in range(0, n, batch_size):
            X_batch = X_shuffled[:, j:j + batch_size]
            Y_batch = Y_shuffled[j:j + batch_size]

            # Lan truyền xuôi
            Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X_batch)

            # Lan truyền ngược
            dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W2, X_batch, Y_batch)

            # Cập nhật trọng số và bias với động lượng
            W1, b1, W2, b2, vW1, vb1, vW2, vb2 = update_params(
                W1, b1, W2, b2, vW1, vb1, vW2, vb2, dW1, db1, dW2, db2, alpha, beta
            )

        # In ra độ chính xác sau mỗi epoch
        if epoch % 1 == 0:
            Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)  # Tính dự đoán trên toàn bộ tập dữ liệu
            predictions = get_predictions(A2)
            accuracy = get_accuracy(predictions, Y)
            print(f"Epoch {epoch+1}/{epochs}, Accuracy: {accuracy:.4f}")

    return W1, b1, W2, b2

In [9]:
# W1, b1, W2, b2 = SGD_with_momentum(X_train_np, y_train_np, 0.01, 500, 32)
W1, b1, W2, b2 = train_with_epoch(X_train_np, y_train_np, 0.01, 200, 32)

[[-0.09632567  0.29410346  0.4167552   0.48367305 -0.23335011 -0.13848667
  -0.06312544  0.3327039 ]
 [ 0.014613   -0.471388    0.36279009 -0.33786768  0.16847865  0.37588258
  -0.13865055 -0.18707956]
 [ 0.49973273 -0.47761057  0.40024849  0.35272857  0.13161087  0.36393201
  -0.1938566   0.34270064]
 [-0.24957719 -0.16166302 -0.47124353 -0.48142115  0.11743805 -0.37446756
   0.41396582 -0.40004341]
 [-0.05060136  0.29774721  0.18901666  0.31851912  0.2925072  -0.14217067
  -0.30245825 -0.4969464 ]
 [ 0.33716056 -0.0238636   0.02750892 -0.17136374  0.47978144  0.02577849
   0.03054197 -0.29501156]
 [-0.13047323 -0.21355492 -0.44048423 -0.01175613 -0.36568597  0.31026739
   0.31483291 -0.28219275]
 [-0.08917135 -0.28289065 -0.12542958  0.38719581  0.10136781 -0.22564543
   0.05070314 -0.04756989]
 [ 0.00668306 -0.23625551 -0.02233102  0.4705161  -0.44749728  0.11595984
   0.27999908  0.02989876]
 [-0.46865147 -0.2420719   0.31907425 -0.40577879 -0.34365808  0.29827661
  -0.3463517   0.

In [10]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_data = X_train_np[:, index, None]
    prediction = make_predictions(X_train_np[:, index, None], W1, b1, W2, b2)
    label = y_train_np[index]
    print("Prediction: ", prediction)
    print("Label: ", label)

In [11]:
test_prediction(111, W1, b1, W2, b2)
test_prediction(250, W1, b1, W2, b2)
test_prediction(235, W1, b1, W2, b2)
test_prediction(300, W1, b1, W2, b2)

Prediction:  [0]
Label:  0
Prediction:  [0]
Label:  0
Prediction:  [1]
Label:  1
Prediction:  [0]
Label:  1


In [12]:
dev_predictions = make_predictions(X_test_np, W1, b1, W2, b2)
get_accuracy(dev_predictions, y_test_np)

0.8034682080924855

In [13]:
print(W1)
print(W2)

[[-0.22291067 -0.74432267  0.01143143  0.48025157 -0.13020832 -1.2228023
  -0.69726986 -0.27587074]
 [-0.00662463 -0.67479306  0.36747814 -0.3249525   0.31776682  0.07575752
  -0.17491836 -0.29578002]
 [ 0.48629191 -0.49815789  0.3102151   0.31702372  0.0978881   0.3518601
  -0.20380987  0.31251452]
 [-0.26853553 -0.23719515 -0.56005487 -0.51489774  0.08858514 -0.4091003
   0.37802422 -0.44991718]
 [ 0.07056271  0.9563392   0.23915846  0.34258988 -0.00420885  0.61884626
  -0.15918098 -0.15171987]
 [ 0.28289461 -0.2435157   0.06612942 -0.16151473  0.66198914 -0.3257591
   0.00806881 -0.42118161]
 [-0.14589899 -0.39953132 -0.39981759  0.00938948 -0.22097085  0.05046148
   0.25871977 -0.36263608]
 [-0.23348774 -0.75190715 -0.55195379  0.22816523  0.05521216 -0.5956305
  -0.15383235 -0.40984834]
 [-0.04840642 -0.50188288 -0.02889141  0.46392217 -0.31464332 -0.19882725
   0.19598365 -0.0968961 ]
 [-0.61948418 -1.0599373   0.61790802 -0.05435058  0.12325305 -0.74928552
  -0.63871825  0.07237